# EXPERIMENT 19 and 20
#Covid Data Analysis
#Divisha Ingavale
#PRN: 25070123043
#ENTC A2

In [28]:
import pandas as pd
import numpy as np

In [29]:
data = pd.read_csv("/content/covid_19_data.csv")
data.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [30]:
data=data.drop(['SNo','Last Update'],axis=1)
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  306429 non-null  object
 1   Province/State   228326 non-null  object
 2   Country/Region   306429 non-null  object
 3   Confirmed        306429 non-null  float64
 4   Deaths           306429 non-null  float64
 5   Recovered        306429 non-null  float64
dtypes: float64(3), object(3)
memory usage: 14.0+ MB

In [ ]:
data['ObservationDate']= data['ObservationDate'].astype('datetime64[ns]')
data['Confirmed']= data['Confirmed'].astype('int64')
data['Deaths']= data['Deaths'].astype('int64')
data['Recovered']= data['Recovered'].astype('int64')
data

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
0,2020-01-22,Anhui,Mainland China,1,0,0,1.0
1,2020-01-22,Beijing,Mainland China,14,0,0,14.0
2,2020-01-22,Chongqing,Mainland China,6,0,0,6.0
3,2020-01-22,Fujian,Mainland China,1,0,0,1.0
4,2020-01-22,Gansu,Mainland China,0,0,0,0.0
...,...,...,...,...,...,...,...
306424,2021-05-29,Zaporizhia Oblast,Ukraine,102641,2335,95289,5017.0
306425,2021-05-29,Zeeland,Netherlands,29147,245,0,28902.0
306426,2021-05-29,Zhejiang,Mainland China,1364,1,1324,39.0
306427,2021-05-29,Zhytomyr Oblast,Ukraine,87550,1738,83790,2022.0
306428,2021-05-29,Zuid-Holland,Netherlands,391559,4252,0,387307.0

In [32]:
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [33]:
###Active case
#Can use this function with the use of pandas
data['Active']=data['Confirmed']-(data['Deaths']+data['Recovered'])
data.head(50)

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
0,01/22/2020,Anhui,Mainland China,1.0,0.0,0.0,1.0
1,01/22/2020,Beijing,Mainland China,14.0,0.0,0.0,14.0
2,01/22/2020,Chongqing,Mainland China,6.0,0.0,0.0,6.0
3,01/22/2020,Fujian,Mainland China,1.0,0.0,0.0,1.0
4,01/22/2020,Gansu,Mainland China,0.0,0.0,0.0,0.0
5,01/22/2020,Guangdong,Mainland China,26.0,0.0,0.0,26.0
6,01/22/2020,Guangxi,Mainland China,2.0,0.0,0.0,2.0
7,01/22/2020,Guizhou,Mainland China,1.0,0.0,0.0,1.0
8,01/22/2020,Hainan,Mainland China,4.0,0.0,0.0,4.0
9,01/22/2020,Hebei,Mainland China,1.0,0.0,0.0,1.0
10,01/22/2020,Heilongjiang,Mainland China,0.0,0.0,0.0,0.0
11,01/22/2020,Henan,Mainland China,5.0,0.0,0.0,5.0
12,01/22/2020,Hong Kong,Hong Kong,0.0,0.0,0.0,0.0
13,01/22/2020,Hubei,Mainland China,444.0,17.0,28.0,399.0
14,01/22/2020,Hunan,Mainland China,4.0,0.0,0.0,4.0
15,01/22/2020,Inner Mongolia,Mainland China,0.0,0.0,0.0,0.0
16,01/22/2020,Jiangsu,Mainland China,1.0,0.0,0.0,1.0
17,01/22/2020,Jiangxi,Mainland China,2.0,0.0,0.0,2.0
18,01/22/2020,Jilin,Mainland China,0.0,0.0,0.0,0.0
19,01/22/2020,Liaoning,Mainland China,2.0,0.0,0.0,2.0
20,01/22/2020,Macau,Macau,1.0,0.0,0.0,1.0
21,01/22/2020,Ningxia,Mainland China,1.0,0.0,0.0,1.0
22,01/22/2020,Qinghai,Mainland China,0.0,0.0,0.0,0.0
23,01/22/2020,Shaanxi,Mainland China,0.0,0.0,0.0,0.0
24,01/22/2020,Shandong,Mainland China,2.0,0.0,0.0,2.0
25,01/22/2020,Shanghai,Mainland China,9.0,0.0,0.0,9.0
26,01/22/2020,Shanxi,Mainland China,1.0,0.0,0.0,1.0
27,01/22/2020,Sichuan,Mainland China,5.0,0.0,0.0,5.0
28,01/22/2020,Taiwan,Taiwan,1.0,0.0,0.0,1.0
29,01/22/2020,Tianjin,Mainland China,4.0,0.0,0.0,4.0
30,01/22/2020,Tibet,Mainland China,0.0,0.0,0.0,0.0
31,01/22/2020,Washington,US,1.0,0.0,0.0,1.0
32,01/22/2020,Xinjiang,Mainland China,0.0,0.0,0.0,0.0
33,01/22/2020,Yunnan,Mainland China,1.0,0.0,0.0,1.0
34,01/22/2020,Zhejiang,Mainland China,10.0,0.0,0.0,10.0
35,01/22/2020,NaN,Japan,2.0,0.0,0.0,2.0
36,01/22/2020,NaN,Thailand,4.0,0.0,2.0,2.0
37,01/22/2020,NaN,South Korea,1.0,0.0,0.0,1.0
38,01/22/2020,Unknown,China,0.0,0.0,0.0,0.0
39,01/22/2020,NaN,Kiribati,0.0,0.0,0.0,0.0
40,01/23/2020,Anhui,Mainland China,9.0,0.0,0.0,9.0
41,01/23/2020,Beijing,Mainland China,22.0,0.0,0.0,22.0
42,01/23/2020,Chongqing,Mainland China,9.0,0.0,0.0,9.0
43,01/23/2020,Fujian,Mainland China,5.0,0.0,0.0,5.0
44,01/23/2020,Gansu,Mainland China,2.0,0.0,0.0,2.0
45,01/23/2020,Guangdong,Mainland China,32.0,0.0,2.0,30.0
46,01/23/2020,Guangxi,Mainland China,5.0,0.0,0.0,5.0
47,01/23/2020,Guizhou,Mainland China,3.0,0.0,0.0,3.0
48,01/23/2020,Hainan,Mainland China,5.0,0.0,0.0,5.0
49,01/23/2020,Hubei,Mainland China,444.0,17.0,28.0,399.0

In [34]:
#iloc( intermidiate data {from where to where})
data.iloc[50:100] #specifies range from where data is to be obtained from

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
50,01/23/2020,Heilongjiang,Mainland China,2.0,0.0,0.0,2.0
51,01/23/2020,Henan,Mainland China,5.0,0.0,0.0,5.0
52,01/23/2020,Hong Kong,Hong Kong,2.0,0.0,0.0,2.0
53,01/23/2020,Hubei,Mainland China,444.0,17.0,28.0,399.0
54,01/23/2020,Hunan,Mainland China,9.0,0.0,0.0,9.0
55,01/23/2020,Inner Mongolia,Mainland China,0.0,0.0,0.0,0.0
56,01/23/2020,Jiangsu,Mainland China,5.0,0.0,0.0,5.0
57,01/23/2020,Jiangxi,Mainland China,7.0,0.0,0.0,7.0
58,01/23/2020,Jilin,Mainland China,1.0,0.0,0.0,1.0
59,01/23/2020,Liaoning,Mainland China,3.0,0.0,0.0,3.0
60,01/23/2020,Macau,Macau,2.0,0.0,0.0,2.0
61,01/23/2020,Ningxia,Mainland China,1.0,0.0,0.0,1.0
62,01/23/2020,Qinghai,Mainland China,0.0,0.0,0.0,0.0
63,01/23/2020,Shaanxi,Mainland China,3.0,0.0,0.0,3.0
64,01/23/2020,Shandong,Mainland China,6.0,0.0,0.0,6.0
65,01/23/2020,Shanghai,Mainland China,16.0,0.0,0.0,16.0
66,01/23/2020,Shanxi,Mainland China,1.0,0.0,0.0,1.0
67,01/23/2020,Sichuan,Mainland China,8.0,0.0,0.0,8.0
68,01/23/2020,Taiwan,Taiwan,1.0,0.0,0.0,1.0
69,01/23/2020,Tianjin,Mainland China,4.0,0.0,0.0,4.0
70,01/23/2020,Tibet,Mainland China,0.0,0.0,0.0,0.0
71,01/23/2020,Washington,US,1.0,0.0,0.0,1.0
72,01/23/2020,Xinjiang,Mainland China,2.0,0.0,0.0,2.0
73,01/23/2020,Yunnan,Mainland China,2.0,0.0,0.0,2.0
74,01/23/2020,Zhejiang,Mainland China,27.0,0.0,0.0,27.0
75,01/23/2020,NaN,Japan,1.0,0.0,0.0,1.0
76,01/23/2020,NaN,Thailand,4.0,0.0,2.0,2.0
77,01/23/2020,NaN,South Korea,1.0,0.0,0.0,1.0
78,01/23/2020,NaN,Singapore,1.0,0.0,0.0,1.0
79,01/23/2020,NaN,Philippines,0.0,0.0,0.0,0.0
80,01/23/2020,NaN,Malaysia,0.0,0.0,0.0,0.0
81,01/23/2020,NaN,Vietnam,2.0,0.0,0.0,2.0
82,01/23/2020,NaN,Australia,0.0,0.0,0.0,0.0
83,01/23/2020,NaN,Mexico,0.0,0.0,0.0,0.0
84,01/23/2020,NaN,Brazil,0.0,0.0,0.0,0.0
85,01/23/2020,NaN,Colombia,0.0,0.0,0.0,0.0
86,01/23/2020,Unknown,China,0.0,0.0,0.0,0.0
87,01/23/2020,NaN,Kiribati,0.0,0.0,0.0,0.0
88,01/24/2020,Hubei,Mainland China,549.0,24.0,31.0,494.0
89,01/24/2020,Guangdong,Mainland China,53.0,0.0,2.0,51.0
90,01/24/2020,Zhejiang,Mainland China,43.0,0.0,1.0,42.0
91,01/24/2020,Beijing,Mainland China,36.0,0.0,1.0,35.0
92,01/24/2020,Chongqing,Mainland China,27.0,0.0,0.0,27.0
93,01/24/2020,Hunan,Mainland China,24.0,0.0,0.0,24.0
94,01/24/2020,Guangxi,Mainland China,23.0,0.0,0.0,23.0
95,01/24/2020,Shanghai,Mainland China,20.0,0.0,1.0,19.0
96,01/24/2020,Jiangxi,Mainland China,18.0,0.0,0.0,18.0
97,01/24/2020,Sichuan,Mainland China,15.0,0.0,0.0,15.0
98,01/24/2020,Shandong,Mainland China,15.0,0.0,0.0,15.0
99,01/24/2020,Anhui,Mainland China,15.0,0.0,0.0,15.0

In [35]:
###last/current data

data['ObservationDate'].max()

'12/31/2020'

In [36]:
### Fetch the latest data
latest_data=data['ObservationDate']== data['ObservationDate'].max
latest_data.head()

0    False
1    False
2    False
3    False
4    False
Name: ObservationDate, dtype: bool

In [37]:
latest_data.shape

(306429,)

In [38]:
latest_date = data['ObservationDate'].max()
latest_data = data[data['ObservationDate'] == latest_date]
latest_data['Country/Region'].value_counts()

Country/Region
Russia                83
US                    58
Japan                 49
India                 37
Colombia              34
                      ..
Venezuela              1
Vietnam                1
West Bank and Gaza     1
Hong Kong              1
Macau                  1
Name: count, Length: 194, dtype: int64

In [39]:
latest_data['Country/Region'].nunique()

194

In [40]:
latest_data['Country/Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Diamond Princess',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See',
       'Honduras', 'Hungary', 'Iceland', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Ivory Coast', 'Jamaica', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'MS Zaandam',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Namibia',
       'Nepal', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Macedonia', 'Norway', 'Oman', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Sri Lanka', 'Sudan', 'Suriname', 'Switzerland',
       'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand',
       'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Uganda', 'United Arab Emirates', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen',
       'Zambia', 'Zimbabwe', 'Italy', 'Brazil', 'Russia', 'Mexico',
       'Japan', 'US', 'Canada', 'Colombia', 'Peru', 'Spain', 'India',
       'UK', 'Mainland China', 'Chile', 'Belgium', 'Netherlands',
       'Australia', 'Pakistan', 'Germany', 'Sweden', 'Ukraine',
       'Hong Kong', 'Macau'], dtype=object)

In [41]:
##Count of cases for each country
countries = latest_data.groupby("Country/Region")[["Confirmed","Deaths","Recovered","Active"]].sum()
countries = countries.reset_index()
countries

         Country/Region  Confirmed  Deaths  Recovered   Active
0           Afghanistan    51526.0  2191.0    41727.0   7608.0
1               Albania    58316.0  1181.0    33634.0  23501.0
2               Algeria    99610.0  2756.0    67127.0  29727.0
3               Andorra     8049.0    84.0     7432.0    533.0
4                Angola    17553.0   405.0    11044.0   6104.0
..                  ...        ...     ...        ...      ...
189             Vietnam     1465.0    35.0     1325.0    105.0
190  West Bank and Gaza   138004.0  1400.0   117183.0  19421.0
191               Yemen     2099.0   610.0     1394.0     95.0
192              Zambia    20725.0   388.0    18660.0   1677.0
193            Zimbabwe    13867.0   363.0    11250.0   2254.0

[194 rows x 5 columns]

In [42]:
countries[countries['Country/Region'] == 'Mainland China']

     Country/Region  Confirmed  Deaths  Recovered  Active
107  Mainland China    87071.0  4634.0    82064.0   373.0

In [43]:
countries[countries['Country/Region'] == 'India']

   Country/Region   Confirmed    Deaths  Recovered    Active
78          India  10266674.0  148738.0  9860280.0  257656.0

In [44]:
countries[countries['Country/Region'] == 'US']

    Country/Region   Confirmed    Deaths  Recovered      Active
181             US  20099363.0  352163.0        0.0  19747200.0

In [45]:
## Plot of world map
import plotly.express as px

world_map = px.choropleth(countries,locations="Country/Region",locationmode="country names",
                          color= "Confirmed", color_continuous_scale="greens", range_color=[0,1000000])
world_map

In [46]:
import plotly.express as px

world_map = px.choropleth(countries,locations="Country/Region",locationmode="country names",
                          color= "Confirmed", color_continuous_scale="blues", range_color=[0,1000000])
world_map

In [47]:
###Top 20 countries having maximum confirmed and recovered cases

top = latest_data.groupby("Country/Region")[['Confirmed','Recovered']].sum().reset_index()
top=top.sort_values(['Confirmed'],ascending=False)
top.head()

    Country/Region   Confirmed  Recovered
181             US  20099363.0        0.0
78           India  10266674.0  9860280.0
23          Brazil   7675973.0  6848844.0
143         Russia   3127347.0  2527722.0
60          France   2677666.0   200142.0

In [48]:
top_20 =top.head(20)
top_20

    Country/Region   Confirmed  Recovered
181             US  20099363.0        0.0
78           India  10266674.0  9860280.0
23          Brazil   7675973.0  6848844.0
143         Russia   3127347.0  2527722.0
60          France   2677666.0   200142.0
180             UK   2496235.0     5482.0
179         Turkey   2208652.0  2100650.0
84           Italy   2107166.0  1463111.0
164          Spain   1928265.0   150376.0
64         Germany   1760520.0  1350708.0
36        Colombia   1642775.0  1508419.0
6        Argentina   1625514.0  1426676.0
116         Mexico   1426094.0  1074795.0
139         Poland   1294878.0  1036138.0
80            Iran   1225142.0   988833.0
183        Ukraine   1086997.0   736611.0
161   South Africa   1057161.0   879671.0
137           Peru   1015137.0   951318.0
125    Netherlands    808382.0     9585.0
79       Indonesia    743198.0   611097.0

In [27]:
### INDIA
India= data[data['Country/Region']=="India"]
India

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
446,2020-01-30,NaN,India,1,0,0,1.0
509,2020-01-31,NaN,India,1,0,0,1.0
567,2020-02-01,NaN,India,1,0,0,1.0
629,2020-02-02,NaN,India,2,0,0,2.0
696,2020-02-03,NaN,India,3,0,0,3.0
...,...,...,...,...,...,...,...
306351,2021-05-29,Tripura,India,50739,507,43190,7042.0
306366,2021-05-29,Unknown,India,0,0,0,0.0
306377,2021-05-29,Uttar Pradesh,India,1688152,20208,1621743,46201.0
306378,2021-05-29,Uttarakhand,India,327112,6360,289642,31110.0
306406,2021-05-29,West Bengal,India,1354956,15268,1237290,102398.0

In [55]:
India['Province/State'].nunique()

38

In [56]:
India['Province/State'].unique()

array([nan, 'Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadar Nagar Haveli', 'Delhi', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Unknown', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Dadra and Nagar Haveli and Daman and Diu',
       'Lakshadweep'], dtype=object)

In [60]:

India['Province/State'] = India['Province/State'].fillna("Mode")
India.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13182 entries, 446 to 306406
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ObservationDate  13182 non-null  datetime64[ns]
 1   Province/State   13182 non-null  object
 2   Country/Region   13182 non-null  object
 3   Confirmed        13182 non-null  int64
 4   Deaths           13182 non-null  int64
 5   Recovered        13182 non-null  int64
 6   Active           13182 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 823.9+ KB

/tmp/ipykernel_830/2581062498.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [61]:
India

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
446,2020-01-30,Mode,India,1,0,0,1.0
509,2020-01-31,Mode,India,1,0,0,1.0
567,2020-02-01,Mode,India,1,0,0,1.0
629,2020-02-02,Mode,India,2,0,0,2.0
696,2020-02-03,Mode,India,3,0,0,3.0
...,...,...,...,...,...,...,...
306351,2021-05-29,Tripura,India,50739,507,43190,7042.0
306366,2021-05-29,Unknown,India,0,0,0,0.0
306377,2021-05-29,Uttar Pradesh,India,1688152,20208,1621743,46201.0
306378,2021-05-29,Uttarakhand,India,327112,6360,289642,31110.0
306406,2021-05-29,West Bengal,India,1354956,15268,1237290,102398.0

In [65]:
India_latest_data=India[India['ObservationDate'] == India['ObservationDate'].max()]
India_latest_data

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
305855,2021-05-29,Andaman and Nicobar Islands,India,6964,113,6660,191.0
305856,2021-05-29,Andhra Pradesh,India,1671742,10738,1487382,173622.0
305873,2021-05-29,Arunachal Pradesh,India,26778,114,22746,3918.0
305874,2021-05-29,Assam,India,403623,3245,344083,56295.0
305896,2021-05-29,Bihar,India,704173,5052,678036,21085.0
305930,2021-05-29,Chandigarh,India,59740,740,56534,2466.0
305937,2021-05-29,Chhattisgarh,India,967645,12979,911752,42914.0
305956,2021-05-29,Dadra and Nagar Haveli and Daman and Diu,India,10214,4,9877,333.0
305960,2021-05-29,Delhi,India,1424646,24073,1387538,13035.0
305996,2021-05-29,Goa,India,154419,2597,136766,15056.0
306012,2021-05-29,Gujarat,India,805617,9790,757124,38703.0
306018,2021-05-29,Haryana,India,753937,8132,722711,23094.0
306025,2021-05-29,Himachal Pradesh,India,188604,3086,168529,16989.0
306051,2021-05-29,Jammu and Kashmir,India,286684,3841,243588,39255.0
306054,2021-05-29,Jharkhand,India,336240,4958,320336,10946.0
306072,2021-05-29,Karnataka,India,2567449,28298,2189064,350087.0
306075,2021-05-29,Kerala,India,2494385,8455,2252505,233425.0
306100,2021-05-29,Ladakh,India,18448,187,16658,1603.0
306101,2021-05-29,Lakshadweep,India,7631,31,5622,1978.0
306121,2021-05-29,Madhya Pradesh,India,777349,7959,738491,30899.0
306127,2021-05-29,Maharashtra,India,5713215,94030,5339838,279347.0
306129,2021-05-29,Manipur,India,48850,776,40044,8030.0
306142,2021-05-29,Meghalaya,India,34448,551,26156,7741.0
306156,2021-05-29,Mizoram,India,11988,36,8863,3089.0
306168,2021-05-29,Nagaland,India,21371,350,16039,4982.0
306212,2021-05-29,Odisha,India,747143,2686,658646,85811.0
306246,2021-05-29,Puducherry,India,102896,1497,88246,13153.0
306250,2021-05-29,Punjab,India,562831,14305,506349,42177.0
306260,2021-05-29,Rajasthan,India,936162,8251,871283,56628.0
306309,2021-05-29,Sikkim,India,14907,247,10829,3831.0
306330,2021-05-29,Tamil Nadu,India,2039716,23261,1706298,310157.0
306334,2021-05-29,Telangana,India,574026,3247,533862,36917.0
306351,2021-05-29,Tripura,India,50739,507,43190,7042.0
306366,2021-05-29,Unknown,India,0,0,0,0.0
306377,2021-05-29,Uttar Pradesh,India,1688152,20208,1621743,46201.0
306378,2021-05-29,Uttarakhand,India,327112,6360,289642,31110.0
306406,2021-05-29,West Bengal,India,1354956,15268,1237290,102398.0

In [68]:
top_state = India_latest_data.groupby("Province/State")[['Confirmed','Recovered']].sum().reset_index()
top_state = top_state.sort_values(['Confirmed'],ascending=False)
top_state.head(20)

    Province/State  Confirmed  Recovered
20     Maharashtra    5713215    5339838
15       Karnataka    2567449    2189064
16          Kerala    2494385    2252505
30      Tamil Nadu    2039716    1706298
34   Uttar Pradesh    1688152    1621743
1   Andhra Pradesh    1671742    1487382
8            Delhi    1424646    1387538
36     West Bengal    1354956    1237290
6     Chhattisgarh     967645     911752
28       Rajasthan     936162     871283
10         Gujarat     805617     757124
19  Madhya Pradesh     777349     738491
11         Haryana     753937     722711
25          Odisha     747143     658646
4            Bihar     704173     678036
31       Telangana     574026     533862
27          Punjab     562831     506349
3            Assam     403623     344083
14       Jharkhand     336240     320336
35     Uttarakhand     327112     289642

In [69]:
top_state['Confirmed'].max()

5713215

In [72]:
top_state[top_state['Confirmed'] == top_state['Confirmed'].max()]['Province/State'].values[0]

'Maharashtra'